name: CI_CD

on: [push]
#  push:
#    branches:
#        - 'test'

#jobs:
#  packer_build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Packer build
#        uses: ExitoLab/packer_build_action_aws@v0.2.10
#        with:
#          templateFile: 'ami.json'
#          workingDir: 'build'
#          varFile: 'variables.json'
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: eu-west-1


  terraform_deploy:
    runs-on: ubuntu-latest
#    needs: packer_build
    defaults:
      run:
        shell: bash
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: list folders
      run: ls -la 

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve # -var-file="dev.auto.tfvars"